<a href="https://colab.research.google.com/github/smargetic/Natural_Language_Processing/blob/main/Machine_Translation/Neural_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nbconvert

In [2]:
#data storage - not sure if important
import pandas as pd

#make sure to show all values in pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

#pytorch
import torch
import torch.nn as nn
import torch.nn.functional as F

#visualize
from IPython.display import display

#help import other functions
import os

#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
##to obtain functions from another .ipynb file

#go to current directory
os.chdir('/content/drive/My Drive/Coding Projects/Machine Translation')

#List the files in the current directory
print('\nFiles currently present:')
print(os.listdir())

#Convert the notebook to a Python script
!jupyter nbconvert --to script intake_preprocess_utils.ipynb
os.rename('intake_preprocess_utils.txt', 'intake_preprocess_utils.py')

print('\n\nNew files in current directory:')
print(os.listdir())
print('\n\n')

#import functions
from intake_preprocess_utils import get_file_and_disp, get_sample, dump_sample, data_preprocessing


Files currently present:
['Neural_Net.ipynb', 'sentences_base.csv', 'ita_sentences_CC0.tsv', 'eng_sentences_detailed.tsv', 'eng_sentences.tsv', 'ita_sentences_detailed.tsv', 'eng_sentences_CC0.tsv', 'ita_sentences.tsv', 'Sentence pairs in English-Italian - 2024-07-26.tsv', 'Helper_Functions.ipynb', 'Model_Train_Predict.ipynb', '__pycache__', 'Data_Intake_and_Preprocessing.ipynb', 'intake_preprocess_utils.ipynb', 'intake_preprocess_utils.py']
[NbConvertApp] Converting notebook intake_preprocess_utils.ipynb to script
[NbConvertApp] Writing 11518 bytes to intake_preprocess_utils.txt


New files in current directory:
['Neural_Net.ipynb', 'sentences_base.csv', 'ita_sentences_CC0.tsv', 'eng_sentences_detailed.tsv', 'eng_sentences.tsv', 'ita_sentences_detailed.tsv', 'eng_sentences_CC0.tsv', 'ita_sentences.tsv', 'Sentence pairs in English-Italian - 2024-07-26.tsv', 'Helper_Functions.ipynb', 'Model_Train_Predict.ipynb', '__pycache__', 'Data_Intake_and_Preprocessing.ipynb', 'intake_preprocess_u

In [ ]:
# #english to italian translation - just to test
# df_eng_it = get_file_and_disp(fileName="Sentence pairs in English-Italian - 2024-07-26.tsv.zip" ,sep='\t', stringName="English to Italian")

In [6]:
#test data set
df = pd.DataFrame({
                  0:[1,2,3],
                  1:["hello world", "how are you", "where are we going"],
                  2:[1,2,3],
                  3: ["ciao mondo", "come stai", "dove stiamo andando"]})

display(df)




0                   1  2                    3
0  1         hello world  1           ciao mondo
1  2         how are you  2            come stai
2  3  where are we going  3  dove stiamo andando

In [7]:
#go through preprocessing
data_dict= data_preprocessing(df.copy(), pytorchB=True, tensorflowB=False, store=False, sample=False, download=False, sing=False)
for key in data_dict.keys():
  print('\n'+key+':')
  display(data_dict[key])

Nulls in English: 0
Nulls in Italian: 0

English/Italian Translations:
	English vocabulary size: 11
	Italian vocabulary size: 10

Done with Pytorch.

English-Italian Dataframe:


eng_id        eng_sentence  it_id          it_sentence  \
0       1         hello world      1           ciao mondo   
1       2         how are you      2            come stai   
2       3  where are we going      3  dove stiamo andando   

                              eng_tokens  \
0           [<sos>, hello, world, <eos>]   
1          [<sos>, how, are, you, <eos>]   
2  [<sos>, where, are, we, going, <eos>]   

                               it_tokens      eng_tokens_enc    it_tokens_enc  \
0            [<sos>, ciao, mondo, <eos>]        [1, 5, 9, 2]     [1, 4, 7, 2]   
1             [<sos>, come, stai, <eos>]    [1, 6, 3, 10, 2]     [1, 5, 8, 2]   
2  [<sos>, dove, stiamo, andando, <eos>]  [1, 8, 3, 7, 4, 2]  [1, 6, 9, 3, 2]   

                                                      eng_tokens_enc_p  \
0   [tensor(1), tensor(5), tensor(9), tensor(2), tensor(0), tensor(0)]   
1  [tensor(1), tensor(6), tensor(3), tensor(10), tensor(2), tensor(0)]   
2   [tensor(1), tensor(8), tensor(3), tensor(7), tensor(4), tensor(2)]   

                                           it_tokens_enc_p  
0  [tensor(1), tensor(4), tensor(7), tensor(2), tensor(0)]  
1  [tensor(1), tensor(5), tensor(8), tensor(2), tensor(0)]  
2  [tensor(1), tensor(6), tensor(9), tensor(3), tensor(2)]


English-Italian SING Dataframe:


None


English-Italian Pytorch Dataloader:



English-Italian TensorFlow Dataloader:


None


English-Italian Pytorch SING Dataloader:


None


English-Italian TensorFlow SING Dataloader:


None


English Vocabulary:


{'<sos>': 1,
 '<eos>': 2,
 'are': 3,
 'going': 4,
 'hello': 5,
 'how': 6,
 'we': 7,
 'where': 8,
 'world': 9,
 'you': 10,
 '<pad>': 0}


Italian Vocabulary:


{'<sos>': 1,
 '<eos>': 2,
 'andando': 3,
 'ciao': 4,
 'come': 5,
 'dove': 6,
 'mondo': 7,
 'stai': 8,
 'stiamo': 9,
 '<pad>': 0}


English Vocabulary SING:


None


Italian Vocabulary SING:


None

In [8]:
#forward input: (batch size (aka. # sentences), # words in sentence (including padding))
#forward output: (batch size (aka. # sentences), # words in sentence (including padding), embedding dim)
class Embedding_Node(nn.Module):
  def __init__(self, vocab_size, embedding_dim):
    super(Embedding_Node, self).__init__()

    self.W_e = nn.Parameter(torch.randn(vocab_size, embedding_dim))

  def forward(self, x):
    return self.W_e[x]

In [9]:
### NOT SURE WHAT THIS IS ---> NEED TO FIX

for input_batch, target_batch in data_dict['English-Italian Pytorch Dataloader']:
  print('\nbatch:')
  display(input_batch)
  display(target_batch)

print('\n\nbatch:')
display(input_batch)
display(target_batch)

#get input and output
input, output = input_batch, target_batch


batch:


tensor([[ 1,  5,  9,  2,  0,  0],
        [ 1,  6,  3, 10,  2,  0],
        [ 1,  8,  3,  7,  4,  2]])

tensor([[1, 4, 7, 2, 0],
        [1, 5, 8, 2, 0],
        [1, 6, 9, 3, 2]])



batch:


tensor([[ 1,  5,  9,  2,  0,  0],
        [ 1,  6,  3, 10,  2,  0],
        [ 1,  8,  3,  7,  4,  2]])

tensor([[1, 4, 7, 2, 0],
        [1, 5, 8, 2, 0],
        [1, 6, 9, 3, 2]])

In [10]:
class Attention_Node(nn.Module):
  def __init__(self,hidden_dim):
    self.hidden_dim = hidden_dim

    #key, query, value
    self.W_key = nn.Linear(hidden_dim, hidden_dim)
    self.W_query = nn.Linear(hidden_dim, hidden_dim)
    self.W_value = nn.Linear(hidden_dim, hidden_dim)

  def forward(self, key_hidden, query_hidden, masked=False):
    #key, query, value
    key = self.W_key(key_hidden)
    query = self.W_query(query_hidden)
    value = self.W_value(key_hidden)

    #get attention scores
    attention_score = torch.matmul(query.T, key)

    #masked - make upper triangle of values negative inf
    if(masked):
      mask = torch.triu(torch.ones_like(attention_score), diagonal=0).bool()
      attention_score[~mask] = float('-inf')

    #softmax
    attention_dist = F.softmax(attention_score, dim=0)

    #attention output - weighted sum
    attention_output = torch.dot(attention_dist, value)

    return attention_output

In [ ]:
# att_node = Attention_Node(embedding_dim)

In [ ]:
class RNN_Node(nn.Module):
  def __init__(self, hidden_dim, embed_dim):
    super(RNN_Node, self).__init__()

    #all parameters that go into the rnn node
    self.layer_weight = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.hidden_weight = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.bias = nn.Parameter(torch.zeros(hidden_dim))

    #store dimensions
    self.hidden_dim = hidden_dim
    self.embed_dim = embed_dim

  #forward pass is how its connected to the next rnn node (regardless of layer or column)
  def forward(self, input, prev_hidden):

    #broadcast bias
    bias = self.bias.expand(input.shape[0], self.hidden_dim)

    #get hidden node
    hidden_node = torch.sigmoid(torch.matmul(self.hidden_weight, prev_hidden.T).T+
                                     torch.matmul(self.layer_weight, input.T).T+
                                     bias) #could also do tanh instead of sigmoid

    return hidden_node


In [ ]:
class LSTM_Node(nn.Module):
  def __init__(self, hidden_dim, embed_dim):
    super(LSTM_Node, self).__init__()

    #forget weight / prev layer forget weight / forget bias
    self.W_f = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_f = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_f = nn.Parameter(torch.zeros(hidden_dim))

    #input weight / prev layer input weight / input bias
    self.W_i = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_i = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_i = nn.Parameter(torch.zeros(hidden_dim))

    #output weight / prev layer output weight / output bis
    self.W_o = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_o = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_o = nn.Parameter(torch.zeros(hidden_dim))

    #cell weight / prev layer cell weight / cell bias
    self.W_c = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_c = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_c = nn.Parameter(torch.zeros(hidden_dim))

    #store dimensions
    self.hidden_dim = hidden_dim
    self.embed_dim = embed_dim


  #forward pass is how its connected to the next lstm node (regardless of layer or column)
  def forward(self, input, prev_hidden, prev_cell):


    #broadcast bias
    b_f = self.b_f.expand(input.shape[0], self.hidden_dim)
    b_i = self.b_i.expand(input.shape[0], self.hidden_dim)
    b_o = self.b_o.expand(input.shape[0], self.hidden_dim)
    b_c = self.b_c.expand(input.shape[0], self.hidden_dim)


    #forget
    f_t = torch.sigmoid(torch.matmul(self.W_f, prev_hidden.T).T+
                                     torch.matmul(self.U_f, input.T).T+
                                     b_f)
    #input
    i_t = torch.sigmoid(torch.matmul(self.W_i, prev_hidden.T).T+
                                     torch.matmul(self.U_i, input.T).T+
                                     b_i)
    #output
    o_t = torch.sigmoid(torch.matmul(self.W_o, prev_hidden.T).T+
                                     torch.matmul(self.U_o, input.T).T+
                                     b_o)

    #new cell data
    nc_t = torch.tanh(torch.matmul(self.W_c, prev_hidden.T).T+
                                     torch.matmul(self.U_c, input.T).T+
                                     b_c)

    #cell
    c_t = f_t*prev_cell + i_t*nc_t

    #hidden
    h_t = o_t*torch.tanh(c_t)

    return h_t, c_t


In [ ]:
def add_norm(prev_x, new_x):
  x = torch.cat(prev_x, new_x, dim=0)
  x = nn.LayerNorm(x)
  return x

In [ ]:
class Transformer_Node(nn.Module):
  def __init__(self, hidden_dim, embed_dim, ff_dim, decoder=False):
    super(Transformer_Node, self).__init__()

    ##layers##
    #attention
    self.attention = Attention_Node(hidden_dim)
    self.decoder = decoder
    if(decoder):
      self.decoder_encoder_att = Attention_Node(hidden_dim)

    #feed forwards
    self.linear1 = nn.Linear(hidden_dim, ff_dim)
    self.linear2 = nn.Linear(ff_dim, hidden_dim)


  #how its connected to the next transformer node
  def forward(self, inputs, encoder_hidden=None):
    #multihead attention (with mask option) ?
    if(self.decoder): # if decoder, only look at values before
      attention_out = self.attention.forward(inputs, inputs, masked=True)
    else:
      attention_out = self.attention.forward(inputs, inputs)

    #add and norm
    x = add_norm(inputs, attention_out)

    #encoder decoder attention
    if(self.decoder):
      x_prev = x
      self.decoder_encoder_att.forward(encoder_hidden, x)
      x = add_norm(x_prev, x)

    x_prev = x
    #feed forward
    x = self.linear1(x)
    x = self.linear2(x)

    #activation function
    x = nn.relu(x)

    #add and norm
    x = add_norm(x_prev, x)

    return x


In [ ]:
# class Transformer_Encoder(nn.Module):
#   def __init__(self, hidden_dim, n_layers, vocab_size):
#     super(Transformer_Encoder, self).__init__()

#     #embedding
#     self.embedding_node = Embedding_Node(vocab_size, hidden_dim)

#     #layers
#     self.layers = nn.ModuleList([Transformer_Node(hidden_dim) for i in range(0,n_layers)])

#   def forward(self, inputs):
#     pass

In [ ]:
# class Transformer_Node(nn.Module):
#   def __init__(self, hidden_dim):
#     super(Transformer_Node, self).__init__()

#   def forward_encoder(self, inputs):
#     pass

#   def forward_decoder(self, inputs):
#     pass

In [ ]:
#for this, we basically said that what should be in the __init__ function should be any parameters that could be learned

#ok, so for node elements, we'll say that in the __init__ funciton we should have the parameters whos weight should be learned
#but for nn layers, well have things that define the layers/ hyperparameters

#__init__ layer = anything that needs to be consistently referenced in forward pass (especially parameters that need to be updated)

In [ ]:
class EncoderNN(nn.Module):
  def __init__(self, node_type, n_layers, hidden_dim, embed_dim, vocab_size):
    super(EncoderNN, self).__init__()

    #model parameters
    self.n_layers = n_layers
    self.node_type = node_type

    #define embedding node
    self.embedding_node = Embedding_Node(vocab_size, embed_dim) # I guess this is one node?

    #create layer of nodes based on type
    if(node_type=="rnn"):
      self.nodes = nn.ModuleList([RNN_Node(hidden_dim, embed_dim) for i in range(0,n_layers)])
    elif(self.node_type=='lstm'):
      self.nodes = nn.ModuleList([LSTM_Node(hidden_dim, embed_dim) for i in range(0,n_layers)])

    # #store initial hidden states
    # self.hidden = torch.randn(n_layers, hidden_dim)
    # self.cell = torch.randn(n_layers, hidden_dim) #only really applicable for lstm

  #define initial hidden states at run time
  def init_hidden(self, batch_size):
    init_hidden_node = [torch.zeros(batch_size, hidden_dim) for _ in range(self.n_layers)]
    init_cell_node = None
    if(self.node_type=="lstm"):
      init_cell_node = [torch.zeros(batch_size, hidden_dim) for _ in range(self.n_layers)]
    return init_hidden_node, init_cell_node


  #forward pass - considered
  def forward(self, inputs):

    #get blank nodes
    node_list = self.nodes
    print('\nNode List')
    display(node_list)

    # #take blank hidden states that define those nodes
    # hidden_list = self.hidden
    # cell_list = self.cell

    #get initial states
    hidden_list, cell_list = self.init_hidden(inputs.shape[0])

    #store final layer hidden nodes (for attention)
    final_hidden_layer = []

    print('\nInitial Input:')
    display(inputs)
    display(inputs.shape)

    #turn input into embedding
    embed_input = self.embedding_node.forward(inputs)
    print('\nEmbedding:')
    # display(embed_input)
    display(embed_input.shape)

    #iterate over each word in sentence (# sent=batch size)
    for i in range(0, embed_input.shape[1]):
      input = embed_input[:,i] #input = (batch_size, hidden_dim) ##1 for each word
      print('\n\nStart of LSTM:')
      print('\nInitial Input:')
      display(input)
      display(input.shape)

      for i in range(0,self.n_layers):
        #if not first word, then previous hidden layer
        if i!=0:
          input = hidden_list[i-1]

          print('\nNew Input:')
          display(input)
          print('input shape: {}'.format(input.shape))

        print('\nHidden List at start of {} layer:'.format(i+1))
        display(hidden_list)
        display(len(hidden_list))

        print('\nHidden List[i]')
        display(hidden_list[i])
        display(hidden_list[i].shape)

        if(cell_list != None):
          print('\n\nCell List:')
          display(cell_list)
          display(len(cell_list))

          print('\nCell List[i]')
          display(cell_list[i])
          display(cell_list[i].shape)

        #forward nodes - hidden_list[i] shape = (batch, hidden dim)
        if(self.node_type=="rnn"):
          hidden_list[i] = node_list[i].forward(input, hidden_list[i]) # (batch, hidden dim)
        elif(self.node_type=='lstm'):
          hidden_list[i], cell_list[i] = node_list[i].forward(input, hidden_list[i], cell_list[i]) # both of size (batch, hidden dim)


        #store final hidden layer
        final_hidden_layer.append(hidden_list[-1])

      break

      outputs = hidden_list if self.node_type=="rnn" else (hidden_list, cell_list) if self.node_type=='lstm' else None

    # for sentence in inputs: #word = (1, # of words w/ pad)
    #   print('\nSentence:')
    #   display(sentence)

    #   #input is initial embedding
    #   input = self.embedding_node.forward(sentence)  #input=(length of word, hidden shape)

    #   print('\nembedding')
    #   display(input)
    #   display(input.shape)
    #   # break

    #   for i in range(0,self.n_layers):
    #     #if not first word, then previous output
    #     if i!=0:
    #       input = hidden_list[i-1]

    #     print('\nHidden List:')
    #     display(hidden_list)
    #     display(hidden_list.shape)

    #     print('\nHidden List[i]')
    #     display(hidden_list[i])
    #     display(hidden_list[i].shape)

    #     #forward nodes
    #     if(self.node_type=="rnn"):
    #       hidden_list[i] = node_list[i].forward(input, hidden_list[i]) # ()
    #     elif(self.node_type=='lstm'):
    #       hidden_list[i], cell_list[i] = node_list[i].forward(input, hidden_list[i], cell_list[i])

    #     print('\nHidden RNN:')
    #     display(hidden_list[i])
    #     display(hidden_list[i].shape)
    #     break

    #   #store final hidden layer
    #   final_hidden_layer.append(hidden_list[-1])


    # outputs = hidden_list if self.node_type=="rnn" else (hidden_list, cell_list) if self.node_type=='lstm' else None

    return outputs, final_hidden_layer

In [ ]:
node_type = "lstm"
n_layers = 2
hidden_dim = 4
embed_dim = 7
#vocab size
eng_vocab_size = len(data_dict["English Vocabulary"])
it_vocab_size = len(data_dict["Italian Vocabulary"])

#create encoder instance
encoder = EncoderNN(node_type, n_layers, hidden_dim, embed_dim, eng_vocab_size)

#forward step
hidden_list, final_hidden_layer = encoder.forward(input)


Node List


ModuleList(
  (0-1): 2 x LSTM_Node()
)


Initial Input:


tensor([[ 1,  8,  3,  7,  4,  2],
        [ 1,  5,  9,  2,  0,  0],
        [ 1,  6,  3, 10,  2,  0]])

torch.Size([3, 6])


Embedding:


torch.Size([3, 6, 7])



Start of LSTM:

Initial Input:


tensor([[-0.2171, -0.1733, -0.4649,  0.2809,  0.4340,  0.2792, -0.2099],
        [-0.2171, -0.1733, -0.4649,  0.2809,  0.4340,  0.2792, -0.2099],
        [-0.2171, -0.1733, -0.4649,  0.2809,  0.4340,  0.2792, -0.2099]],
       grad_fn=<SelectBackward0>)

torch.Size([3, 7])


Hidden List at start of 1 layer:


[tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]])]

2


Hidden List[i]


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.Size([3, 4])



Cell List:


[tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]])]

2


Cell List[i]


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.Size([3, 4])


New Input:


tensor([[-0.1025,  0.0467, -0.0173,  0.3402],
        [-0.1025,  0.0467, -0.0173,  0.3402],
        [-0.1025,  0.0467, -0.0173,  0.3402]], grad_fn=<MulBackward0>)

input shape: torch.Size([3, 4])

Hidden List at start of 2 layer:


[tensor([[-0.1025,  0.0467, -0.0173,  0.3402],
         [-0.1025,  0.0467, -0.0173,  0.3402],
         [-0.1025,  0.0467, -0.0173,  0.3402]], grad_fn=<MulBackward0>),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]])]

2


Hidden List[i]


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.Size([3, 4])



Cell List:


[tensor([[-0.2350,  0.0579, -0.0251,  0.7322],
         [-0.2350,  0.0579, -0.0251,  0.7322],
         [-0.2350,  0.0579, -0.0251,  0.7322]], grad_fn=<AddBackward0>),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]])]

2


Cell List[i]


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.Size([3, 4])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x7 and 4x3)

In [ ]:
# input

In [ ]:
# #forward step
# hidden_list, final_hidden_layer = encoder.forward(input)

In [ ]:
class DecoderNN(nn.Module):
  def __init__(self, node_type, n_layers, hidden_dim, vocab_size, attention=False, max_length=30):
    super(DecoderNN, self).__init__()

    #model parameters
    self.n_layers = n_layers
    self.node_type = node_type
    self.max_length = max_length

    #define embedding node
    self.embedding_node = Embedding_Node(vocab_size, hidden_dim) # I guess this is one node?

    #create layer of nodes based on type
    if(node_type=="rnn"):
      self.nodes = nn.ModuleList([RNN_Node(hidden_dim) for i in range(0,n_layers)])
    else:
      self.nodes = nn.ModuleList([LSTM_Node(hidden_dim) for i in range(0,n_layers)])

    # #store initial hidden states
    # #self.hidden = torch.randn(n_layers, hidden_dim)
    # self.cell = torch.randn(n_layers, hidden_dim) #only really applicable for lstm
    self.prev_hidden = torch.randn(n_layers, hidden_dim)
    self.prev_cell = torch.randn(n_layers, hidden_dim) #only really applicable for lstm


    #output weights
    self.W_out = nn.Parameter(torch.randn(vocab_size, hidden_dim))

    #attention
    self.attention = attention
    if(attention):
      self.attention_node = Attention_Node(hidden_dim)

  #forward pass - must iterate over
  def forward(self, input, prev_hidden, prev_cell=None, encoder_flayer=None):
    #start with blank hidden and cell states
    hidden_list = self.prev_hidden
    cell_list = self.prev_cell

    #depending on the length, replace hidden and cell states
    hidden_list[:len(prev_hidden)] = prev_hidden
    if(prev_cell!=None):
      cell_list[:len(prev_cell)] = prev_cell

    #initial nodes
    node_list = self.nodes

    #get embedding of input
    input = self.embedding_node.forward(input)


    #put input through all layers
    for i in range(0,self.n_layers):
      if(self.node_type=='rnn'):
        hidden_list[i] = node_list[i].forward(input, hidden_list[i])
      elif (self.node_type=='lstm'):
        hidden_list[i], cell_list[i] = node_list[i].forward(input, hidden_list[i], cell_list[i])

      #new input is prev output
      input = hidden_list[i]

    #attention
    if(self.attention):
      attention_out = self.attention_node.forward(encoder_flayer, hidden_list[-1])
      hidden_list[-1] = torch.cat((hidden_list[-1], attention_out), dim=0)

    #generate final output
    output = torch.dot(self.W_out, hidden_list[-1])

    return output, hidden_list, cell_list

  #to generate predictions - could either do this step by step, or generate all predictions in one go
  def pred(self, hidden_list, cell_list=None, encoder_flayer=None):
    output_list = []
    input = 0 # <sos> = start of sentence

    #keep predicting unless reach max_length or break out clause
    for count in range(0,self.max_length):
      input, hidden_list, cell_list = self.forward(input, hidden_list, cell_list)

      output_list.append(input)

      #<eos>
      if(input==1):
        break

    # #turn into tensor
    # output_list = torch.cat(output_list, dim=0)
    # display(output_list)

    #attention
    if(self.attention):
      attention_out = self.attention_node.forward(encoder_flayer, output_list)
      output_list = torch.cat((output_list, attention_out), dim=0)
    else: #DOUBLE CHECK ON THIS
      output_list = torch.cat(output_list, dim=0)

    #put through softmax
    output_list = F.softmax(output_list, dim=0)

    return output_list


In [ ]:
class Seq2Seq(nn.Module):
  def __init__(self, encoder_args, decoder_args):
    super(Seq2Seq, self).__init__()

    #model structure
    self.encoder = EncoderNN(*encoder_args)
    self.decoder = DecoderNN(*decoder_args)

    #set other model params to be ref later
    self.encoder.node_type = encoder_args[0]
    self.decoder.node_type = decoder_args[0]


  #for the full system
  def forward(self, inputs, outputs):

    #encoder
    if (self.encoder.node_type == "rnn"):
      hidden_list, final_hidden_layer = self.encoder.forward(inputs)
      cell_list = None
    elif (self.encoder.node_type == "lstm"):
      hidden_list, cell_list, final_hidden_layer = self.encoder.forward(inputs)

    #decoder
    pred_out = []
    for i in range(0, len(outputs)):
      if(self.decoder.node_type == "rnn"):
        pred_out[i], hidden_list, cell_list = self.decoder.forward(input=outputs[i], prev_hidden=hidden_list, encoder_flayer=final_hidden_layer)
      elif (self.decoder.node_type == "lstm")
        pred_out[i], hidden_list, cell_list = self.decoder.forward(input=outputs[i], prev_hidden=hidden_list, prev_cell=cell_list, encoder_flayer=final_hidden_layer)


    return pred_out #must make sure has shape (batch size, seq length, vocab size)


  def pred(self, inputs):
    # #encoder
    if (self.encoder.node_type == "rnn"):
      hidden_list, final_hidden_layer = self.encoder.forward(inputs)
      cell_list = None
    elif (self.encoder.node_type == "lstm"):
      hidden_list, cell_list, final_hidden_layer = self.encoder.forward(inputs)

    #decoder
    if (self.decoder.node_type == "rnn"):
      pred_out = self.decoder.pred(hidden_list, encoder_flayer=final_hidden_layer)
    elif (self.decoder.node_type == "lstm"):
      pred_out = self.decoder.pred(hidden_list, cell_list, encoder_flayer=final_hidden_layer)

    return pred_out

    #input to decoder depends on what the encoder was

    # #decoder
    # if(self.decoder.node_type == "rnn"):
    #   outputs = self.decoder.forward(hidden_list)
    # else:
    #   outputs = self.decoder.forward(hidden_list, cell_list)

    #attention


    # return outputs


Notes:

- before running - write in comments how each dimension is looking like after each computation - helpful for debugging

- incorporate batches!

- transformers

- beam search

- bidirectional

- different attention methods

-- evaluate with Bleu scores

Run time notes:

- embedding size: Common values for the embedding dimension in NLP tasks range from 50 to 300, but larger values like 512 or 1024 can be used for more complex tasks or larger datasets.