<a href="https://colab.research.google.com/github/smargetic/Natural_Language_Processing/blob/main/Machine_Translation/Neural_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [177]:
!pip install nbconvert

In [178]:
#data storage - not sure if important
import pandas as pd
import numpy as np #can take away later

#make sure to show all values in pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

#pytorch
import torch
import torch.nn as nn
import torch.nn.functional as F

#visualize
from IPython.display import display

#help import other functions
import os

#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [179]:
##to obtain functions from another .ipynb file

#go to current directory
os.chdir('/content/drive/My Drive/Coding Projects/Machine Translation')

#List the files in the current directory
print('\nFiles currently present:')
print(os.listdir())

#Convert the notebook to a Python script
!jupyter nbconvert --to script intake_preprocess_utils.ipynb
os.rename('intake_preprocess_utils.txt', 'intake_preprocess_utils.py')

print('\n\nNew files in current directory:')
print(os.listdir())
print('\n\n')

#import functions
from intake_preprocess_utils import get_file_and_disp, get_sample, dump_sample, data_preprocessing


Files currently present:
['sentences_base.csv', 'ita_sentences_CC0.tsv', 'eng_sentences_detailed.tsv', 'eng_sentences.tsv', 'ita_sentences_detailed.tsv', 'eng_sentences_CC0.tsv', 'ita_sentences.tsv', 'Sentence pairs in English-Italian - 2024-07-26.tsv', 'Helper_Functions.ipynb', 'Model_Train_Predict.ipynb', '__pycache__', 'Data_Intake_and_Preprocessing.ipynb', 'intake_preprocess_utils.ipynb', 'intake_preprocess_utils.py', 'Neural_Net.ipynb']
[NbConvertApp] Converting notebook intake_preprocess_utils.ipynb to script
[NbConvertApp] Writing 11518 bytes to intake_preprocess_utils.txt


New files in current directory:
['sentences_base.csv', 'ita_sentences_CC0.tsv', 'eng_sentences_detailed.tsv', 'eng_sentences.tsv', 'ita_sentences_detailed.tsv', 'eng_sentences_CC0.tsv', 'ita_sentences.tsv', 'Sentence pairs in English-Italian - 2024-07-26.tsv', 'Helper_Functions.ipynb', 'Model_Train_Predict.ipynb', '__pycache__', 'Data_Intake_and_Preprocessing.ipynb', 'intake_preprocess_utils.ipynb', 'intake

In [180]:
# #english to italian translation - just to test
# df_eng_it = get_file_and_disp(fileName="Sentence pairs in English-Italian - 2024-07-26.tsv.zip" ,sep='\t', stringName="English to Italian")

In [181]:
#test data set
df = pd.DataFrame({
                  0:[1,2,3],
                  1:["hello world", "how are you", "where are we going"],
                  2:[1,2,3],
                  3: ["ciao mondo", "come stai", "dove stiamo andando"]})

display(df)




0                   1  2                    3
0  1         hello world  1           ciao mondo
1  2         how are you  2            come stai
2  3  where are we going  3  dove stiamo andando

In [182]:
#go through preprocessing
data_dict= data_preprocessing(df.copy(), pytorchB=True, tensorflowB=False, store=False, sample=False, download=False, sing=False)
for key in data_dict.keys():
  print('\n'+key+':')
  display(data_dict[key])

Nulls in English: 0
Nulls in Italian: 0

English/Italian Translations:
	English vocabulary size: 11
	Italian vocabulary size: 10

Done with Pytorch.

English-Italian Dataframe:


eng_id        eng_sentence  it_id          it_sentence  \
0       1         hello world      1           ciao mondo   
1       2         how are you      2            come stai   
2       3  where are we going      3  dove stiamo andando   

                              eng_tokens  \
0           [<sos>, hello, world, <eos>]   
1          [<sos>, how, are, you, <eos>]   
2  [<sos>, where, are, we, going, <eos>]   

                               it_tokens      eng_tokens_enc    it_tokens_enc  \
0            [<sos>, ciao, mondo, <eos>]        [1, 5, 9, 2]     [1, 4, 7, 2]   
1             [<sos>, come, stai, <eos>]    [1, 6, 3, 10, 2]     [1, 5, 8, 2]   
2  [<sos>, dove, stiamo, andando, <eos>]  [1, 8, 3, 7, 4, 2]  [1, 6, 9, 3, 2]   

                                                      eng_tokens_enc_p  \
0   [tensor(1), tensor(5), tensor(9), tensor(2), tensor(0), tensor(0)]   
1  [tensor(1), tensor(6), tensor(3), tensor(10), tensor(2), tensor(0)]   
2   [tensor(1), tensor(8), tensor(3), tensor(7), tensor(4), tensor(2)]   

                                           it_tokens_enc_p  
0  [tensor(1), tensor(4), tensor(7), tensor(2), tensor(0)]  
1  [tensor(1), tensor(5), tensor(8), tensor(2), tensor(0)]  
2  [tensor(1), tensor(6), tensor(9), tensor(3), tensor(2)]


English-Italian SING Dataframe:


None


English-Italian Pytorch Dataloader:



English-Italian TensorFlow Dataloader:


None


English-Italian Pytorch SING Dataloader:


None


English-Italian TensorFlow SING Dataloader:


None


English Vocabulary:


{'<sos>': 1,
 '<eos>': 2,
 'are': 3,
 'going': 4,
 'hello': 5,
 'how': 6,
 'we': 7,
 'where': 8,
 'world': 9,
 'you': 10,
 '<pad>': 0}


Italian Vocabulary:


{'<sos>': 1,
 '<eos>': 2,
 'andando': 3,
 'ciao': 4,
 'come': 5,
 'dove': 6,
 'mondo': 7,
 'stai': 8,
 'stiamo': 9,
 '<pad>': 0}


English Vocabulary SING:


None


Italian Vocabulary SING:


None

In [183]:
#forward input: (batch size (aka. # sentences), # words in sentence (including padding))
#forward output: (batch size (aka. # sentences), # words in sentence (including padding), embedding dim)
class Embedding_Node(nn.Module):
  def __init__(self, vocab_size, embedding_dim):
    super(Embedding_Node, self).__init__()

    self.W_e = nn.Parameter(torch.randn(vocab_size, embedding_dim))

  def forward(self, x):
    return self.W_e[x]

In [184]:
### Seperates data into batches --> NEED TO GO OVER

for input_batch, target_batch in data_dict['English-Italian Pytorch Dataloader']:
  print('\nbatch:')
  display(input_batch)
  display(target_batch)

print('\n\nbatch:')
display(input_batch)
display(target_batch)

#get input and output
input, output = input_batch, target_batch


batch:


tensor([[ 1,  8,  3,  7,  4,  2],
        [ 1,  5,  9,  2,  0,  0],
        [ 1,  6,  3, 10,  2,  0]])

tensor([[1, 6, 9, 3, 2],
        [1, 4, 7, 2, 0],
        [1, 5, 8, 2, 0]])



batch:


tensor([[ 1,  8,  3,  7,  4,  2],
        [ 1,  5,  9,  2,  0,  0],
        [ 1,  6,  3, 10,  2,  0]])

tensor([[1, 6, 9, 3, 2],
        [1, 4, 7, 2, 0],
        [1, 5, 8, 2, 0]])

In [185]:
class Attention_Node(nn.Module):
  def __init__(self,hidden_dim):
    self.hidden_dim = hidden_dim

    #key, query, value
    self.W_key = nn.Linear(hidden_dim, hidden_dim)
    self.W_query = nn.Linear(hidden_dim, hidden_dim)
    self.W_value = nn.Linear(hidden_dim, hidden_dim)

  def forward(self, key_hidden, query_hidden, masked=False):
    #key, query, value
    key = self.W_key(key_hidden)
    query = self.W_query(query_hidden)
    value = self.W_value(key_hidden)

    #get attention scores
    attention_score = torch.matmul(query.T, key)

    #masked - make upper triangle of values negative inf
    if(masked):
      mask = torch.triu(torch.ones_like(attention_score), diagonal=0).bool()
      attention_score[~mask] = float('-inf')

    #softmax
    attention_dist = F.softmax(attention_score, dim=0)

    #attention output - weighted sum
    attention_output = torch.dot(attention_dist, value)

    return attention_output

In [186]:
# att_node = Attention_Node(embedding_dim)

In [187]:
class RNN_Node(nn.Module):
  def __init__(self, hidden_dim, input_dim):
    super(RNN_Node, self).__init__()

    #all parameters that go into the rnn node
    self.layer_weight = nn.Parameter(torch.randn(hidden_dim, input_dim))
    self.hidden_weight = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.bias = nn.Parameter(torch.zeros(hidden_dim))

    #store dimensions
    self.hidden_dim = hidden_dim
    self.input_dim = input_dim

  #forward pass is how its connected to the next rnn node (regardless of layer or column)
  def forward(self, input, prev_hidden):
    #broadcast bias
    bias = self.bias.expand(input.shape[0], self.hidden_dim)

    #get hidden node
    hidden_node = torch.sigmoid(torch.matmul(self.hidden_weight, prev_hidden.T).T+
                                     torch.matmul(self.layer_weight, input.T).T+
                                     bias) #could also do tanh instead of sigmoid

    return hidden_node


In [188]:
class LSTM_Node(nn.Module):
  def __init__(self, hidden_dim, embed_dim):
    super(LSTM_Node, self).__init__()

    #forget weight / prev layer forget weight / forget bias
    self.W_f = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_f = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_f = nn.Parameter(torch.zeros(hidden_dim))

    #input weight / prev layer input weight / input bias
    self.W_i = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_i = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_i = nn.Parameter(torch.zeros(hidden_dim))

    #output weight / prev layer output weight / output bis
    self.W_o = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_o = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_o = nn.Parameter(torch.zeros(hidden_dim))

    #cell weight / prev layer cell weight / cell bias
    self.W_c = nn.Parameter(torch.randn(hidden_dim, hidden_dim))
    self.U_c = nn.Parameter(torch.randn(hidden_dim, embed_dim))
    self.b_c = nn.Parameter(torch.zeros(hidden_dim))

    #store dimensions
    self.hidden_dim = hidden_dim
    self.embed_dim = embed_dim


  #forward pass is how its connected to the next lstm node (regardless of layer or column)
  def forward(self, input, prev_hidden, prev_cell):


    #broadcast bias
    b_f = self.b_f.expand(input.shape[0], self.hidden_dim)
    b_i = self.b_i.expand(input.shape[0], self.hidden_dim)
    b_o = self.b_o.expand(input.shape[0], self.hidden_dim)
    b_c = self.b_c.expand(input.shape[0], self.hidden_dim)


    #forget
    f_t = torch.sigmoid(torch.matmul(self.W_f, prev_hidden.T).T+
                                     torch.matmul(self.U_f, input.T).T+
                                     b_f)
    #input
    i_t = torch.sigmoid(torch.matmul(self.W_i, prev_hidden.T).T+
                                     torch.matmul(self.U_i, input.T).T+
                                     b_i)
    #output
    o_t = torch.sigmoid(torch.matmul(self.W_o, prev_hidden.T).T+
                                     torch.matmul(self.U_o, input.T).T+
                                     b_o)

    #new cell data
    nc_t = torch.tanh(torch.matmul(self.W_c, prev_hidden.T).T+
                                     torch.matmul(self.U_c, input.T).T+
                                     b_c)

    #cell
    c_t = f_t*prev_cell + i_t*nc_t

    #hidden
    h_t = o_t*torch.tanh(c_t)

    return h_t, c_t


In [189]:
def add_norm(prev_x, new_x):
  x = torch.cat(prev_x, new_x, dim=0)
  x = nn.LayerNorm(x)
  return x

In [190]:
class Transformer_Node(nn.Module):
  def __init__(self, hidden_dim, embed_dim, ff_dim, decoder=False):
    super(Transformer_Node, self).__init__()

    ##layers##
    #attention
    self.attention = Attention_Node(hidden_dim)
    self.decoder = decoder
    if(decoder):
      self.decoder_encoder_att = Attention_Node(hidden_dim)

    #feed forwards
    self.linear1 = nn.Linear(hidden_dim, ff_dim)
    self.linear2 = nn.Linear(ff_dim, hidden_dim)


  #how its connected to the next transformer node
  def forward(self, inputs, encoder_hidden=None):
    #multihead attention (with mask option) ?
    if(self.decoder): # if decoder, only look at values before
      attention_out = self.attention.forward(inputs, inputs, masked=True)
    else:
      attention_out = self.attention.forward(inputs, inputs)

    #add and norm
    x = add_norm(inputs, attention_out)

    #encoder decoder attention
    if(self.decoder):
      x_prev = x
      self.decoder_encoder_att.forward(encoder_hidden, x)
      x = add_norm(x_prev, x)

    x_prev = x
    #feed forward
    x = self.linear1(x)
    x = self.linear2(x)

    #activation function
    x = nn.relu(x)

    #add and norm
    x = add_norm(x_prev, x)

    return x


In [191]:
# class Transformer_Encoder(nn.Module):
#   def __init__(self, hidden_dim, n_layers, vocab_size):
#     super(Transformer_Encoder, self).__init__()

#     #embedding
#     self.embedding_node = Embedding_Node(vocab_size, hidden_dim)

#     #layers
#     self.layers = nn.ModuleList([Transformer_Node(hidden_dim) for i in range(0,n_layers)])

#   def forward(self, inputs):
#     pass

In [192]:
# class Transformer_Node(nn.Module):
#   def __init__(self, hidden_dim):
#     super(Transformer_Node, self).__init__()

#   def forward_encoder(self, inputs):
#     pass

#   def forward_decoder(self, inputs):
#     pass

In [193]:
#for this, we basically said that what should be in the __init__ function should be any parameters that could be learned

#ok, so for node elements, we'll say that in the __init__ funciton we should have the parameters whos weight should be learned
#but for nn layers, well have things that define the layers/ hyperparameters

#__init__ layer = anything that needs to be consistently referenced in forward pass (especially parameters that need to be updated)

In [194]:
  # #define initial hidden states at run time - b/c of batch size
  # def init_hidden(self, batch_size):
  #   init_hidden_list = [torch.zeros(batch_size, self.hidden_dim) for _ in range(self.n_layers)]
  #   init_cell_list = None
  #   if(self.node_type=="lstm"):
  #     init_cell_list = [torch.zeros(batch_size, self.hidden_dim) for _ in range(self.n_layers)]
  #   return init_hidden_list, init_cell_list

In [195]:
#define initial hidden states at run time - b/c of batch size
def init_hidden(self, batch_size):
  #get device
  device = next(self.parameters()).device

  #itialize tens based on node type
  init_hidden_tensor = torch.zeros(self.n_layers, batch_size, self.hidden_dim).to(device)
  init_cell_tensor = None
  if(self.node_type=="lstm"):
    init_cell_tensor = torch.zeros(self.n_laryers, batch_size, self.hidden_dim).to(device)
  return init_hidden_tensor, init_cell_tensor

In [196]:
# input.shape[1]

In [197]:
class EncoderNN(nn.Module):
  def __init__(self, node_type, n_layers, hidden_dim, embed_dim, vocab_size):
    super(EncoderNN, self).__init__()
    # self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #model parameters
    self.n_layers = n_layers
    self.node_type = node_type
    self.hidden_dim = hidden_dim

    #define embedding node
    self.embedding_node = Embedding_Node(vocab_size, embed_dim)


    #create layer of nodes based on type
    node_class = RNN_Node if node_type == "rnn" else LSTM_Node
    self.nodes = nn.ModuleList(
          [node_class(hidden_dim, embed_dim)] +
          [node_class(hidden_dim, hidden_dim) for _ in range(n_layers - 1)])

  # #define initial hidden states at run time - b/c of batch size
  # def init_hidden(self, batch_size):
  #   init_hidden_node = [torch.zeros(batch_size, self.hidden_dim) for _ in range(self.n_layers)]
  #   init_cell_node = None
  #   if(self.node_type=="lstm"):
  #     init_cell_node = [torch.zeros(batch_size, self.hidden_dim) for _ in range(self.n_layers)]
  #   return init_hidden_node, init_cell_node


  #forward pass
  def forward(self, inputs):

    #get blank nodes
    node_list = self.nodes

    #get shape params
    batch_size = inputs.shape[0]
    seq_size = inputs.shape[1]

    #get initial states
    # hidden_list, cell_list = self.init_hidden(inputs.shape[0])
    hidden_tensor, cell_tensor = init_hidden(self, batch_size)
    last_layer_hidden = torch.zeros(batch_size, seq_size, self.hidden_dim)

    #turn input into embedding
    embed_input = self.embedding_node.forward(inputs)

    # print('this is the embedding inputs:')
    # display(embed_input)

    #store final layer hidden nodes (for attention)
    # final_hidden_layer = []
    # final_hidden_tensor = torch.zeros(batch_size, )

    #iterate over each word in sentence
    for word_i in range(0, seq_size):

      input = embed_input[:,word_i] #input = (batch_size, hidden_dim) ##1 for each word

      for layer in range(0,self.n_layers):
        #if not first layer, then input is previous hidden state
        if layer!=0:
          input = hidden_tensor[layer-1]

        #TRY TO SEE IF CAN MAKE NEATER
        #forward pass -- TRY TO FIX LATER - AFTER TRANSFORMER
        if(self.node_type=="rnn"):
          hidden_tensor[layer] = node_list[layer].forward(input, hidden_tensor[layer]) # (batch, hidden dim)
        elif(self.node_type=='lstm'):
          hidden_tensor[layer], cell_tensor[layer] = node_list[layer].forward(input, hidden_tensor[layer], cell_tensor[layer]) # both of size (batch, hidden dim)

      #store final hidden layer for each word - for attention
      last_layer_hidden[:, word_i, :self.hidden_dim] = hidden_tensor[-1]

    #format outputs
    outputs = (hidden_tensor[-1], None) if self.node_type=="rnn" else (hidden_tensor[-1], cell_tensor[-1]) if self.node_type=='lstm' else None

    return outputs, last_layer_hidden

In [198]:
class DecoderNN(nn.Module):
  def __init__(self, node_type, n_layers, hidden_dim, embed_dim, vocab_size, attention=False):
    super(DecoderNN, self).__init__()

    #model parameters
    self.n_layers = n_layers
    self.node_type = node_type
    # self.max_length = max_length
    self.hidden_dim = hidden_dim
    self.vocab_size = vocab_size

    #define embedding node
    self.embedding_node = Embedding_Node(vocab_size, embed_dim)

    #create layer of nodes based on type
    node_class = RNN_Node if node_type == "rnn" else LSTM_Node
    self.nodes = nn.ModuleList(
          [node_class(hidden_dim, embed_dim)] +
          [node_class(hidden_dim, hidden_dim) for _ in range(n_layers - 1)])


    # # #store initial hidden states
    # # #self.hidden = torch.randn(n_layers, hidden_dim)
    # # self.cell = torch.randn(n_layers, hidden_dim) #only really applicable for lstm
    # self.prev_hidden = torch.randn(n_layers, hidden_dim)
    # self.prev_cell = torch.randn(n_layers, hidden_dim) #only really applicable for lstm


    #output weights
    self.W_out = nn.Parameter(torch.randn(vocab_size, hidden_dim))

    #attention
    self.attention = attention
    if(attention):
      self.attention_node = Attention_Node(hidden_dim)


  # #define initial hidden states at run time - b/c of batch size
  # def init_hidden(self, batch_size):
  #   init_hidden_list = [torch.zeros(batch_size, hidden_dim) for _ in range(self.n_layers)]
  #   init_cell_list = None
  #   if(self.node_type=="lstm"):
  #     init_cell_list = [torch.zeros(batch_size, hidden_dim) for _ in range(self.n_layers)]
  #   return init_hidden_list, init_cell_list

  #forward pass - considered as going over one word (versus encoder going over entire sentence) - training
  def forward(self, input, hidden_tensor, cell_tensor=None, encoder_flayer=None):
    #initial nodes
    node_list = self.nodes

    print('\nthis is the initial input of the decoder forward')
    display(input)
    print("this is the type: {}".format(type(input)))
    print('this is the shape: {}\n\n\n'.format(input.shape))

    #get embedding of input
    input = self.embedding_node.forward(input)[:,0] #only take one word

    #forward pass for all layers (remember - not entire sentence, just 1 word)
    for layer in range(0,self.n_layers):
      #if not first layer, then input is previous hidden state
      if layer!=0:
        input = hidden_tensor[layer-1]

      #forward pass
      if(self.node_type=="rnn"):
        hidden_tensor[layer] = node_list[layer].forward(input, hidden_tensor[layer]) # (batch, hidden dim)
      elif(self.node_type=='lstm'):
        hidden_tensor[layer], cell_tensor[layer] = node_list[layer].forward(input, hidden_tensor[layer], cell_tensor[layer]) # both of size (batch, hidden dim)


    #COME BACK TO ATTENTION
    #attention
    # if(self.attention):
    #   attention_out = self.attention_node.forward(encoder_flayer, hidden_list[-1])
    #   hidden_list[-1] = torch.cat((hidden_list[-1], attention_out), dim=0)

    #generate final output
    pred_output = torch.matmul(self.W_out, hidden_tensor[-1].T).T #during training - cross entropy fun converts this to prob

    return hidden_tensor, cell_tensor, pred_output

  #to generate predictions - generate one word at a time
  #greedy decoding - uses/ predicts most probable word
  def pred(self, prev_input, hidden_tensor, cell_tensor=None, encoder_flayer=None):
    #generate predicted word & others
    hidden_tensor, cell_tensor, pred_logit = self.forward(prev_input, hidden_tensor, cell_tensor, encoder_flayer)

    print('this is the predicted logits')
    display(pred_logit)
    print('pred logit shape: {}'.format(pred_logit.shape))

    #convert logits to prob
    pred_prob = F.softmax(pred_logit, dim=1) #should be correct

    print('this is the preicted probabilities ')
    display(pred_prob)
    print('pred prob shape: {}'.format(pred_prob.shape))

    #get most prob word
    _, pred_word_indx = torch.max(pred_prob, dim=1)

    print('this is the predicted words:')
    display(pred_word_indx)
    print('pred_words shape: {}'.format(pred_word_indx.shape))

    return hidden_tensor, cell_tensor, pred_word_indx


In [199]:
class Seq2Seq(nn.Module):
  def __init__(self, encoder_args, decoder_args, max_length=30, sos_token=1, eos_token=2):
    super(Seq2Seq, self).__init__()

    #model structure
    self.encoder = EncoderNN(*encoder_args)
    self.decoder = DecoderNN(*decoder_args)

    # #set other model params to be ref later
    # self.encoder.node_type = encoder_args[0]
    # self.decoder.node_type = decoder_args[0]

    #set other model params to be ref later
    self.max_length = max_length
    self.sos_token = sos_token
    self.eos_token = eos_token


    # Linear layer to project encoder hidden dim to decoder hidden dim
    enc_hid = encoder_args[2]
    dec_hid = decoder_args[2]
    self.hidden_transform = nn.Linear(enc_hid, dec_hid)
    self.cell_transform = nn.Linear(enc_hid, dec_hid)

  #run encoder and initialize decoder with hidden states
  def run_enc_init_dec(self, inputs):
    #put on correct device
    device = next(self.parameters()).device
    inputs = inputs.to(device)

    #encoder
    node_class = RNN_Node if self.encoder.node_type == "rnn" else LSTM_Node
    (enc_hidden_node, enc_cell_node), enc_final_hidden_layer = self.encoder.forward(inputs)

    #initialize hidden and cell tensor
    dec_hidden_tensor, dec_cell_tensor = init_hidden(self.decoder, inputs.shape[0])

    #linear transform encoder return values - in case hidden sizes don't match
    dec_hidden_tensor[0] = self.hidden_transform(enc_hidden_node)
    if (dec_cell_tensor!=None) and (enc_cell_node!=None):
      dec_cell_tensor[0] = self.cell_transform(enc_cell_node)

    return dec_hidden_tensor, dec_cell_tensor, enc_final_hidden_layer


  #for the full system
  def forward(self, inputs, outputs):
    #put on correct device
    device = next(self.parameters()).device
#    inputs = inputs.to(device)
    outputs = outputs.to(device)

    # #encoder
    # node_class = RNN_Node if self.encoder.node_type == "rnn" else LSTM_Node
    # (enc_hidden_node, enc_cell_node), enc_final_hidden_layer = self.encoder.forward(inputs)

    # #initialize hidden and cell tensor
    # dec_hidden_tensor, dec_cell_tensor = init_hidden(self.decoder, inputs.shape[0])

    # #linear transform encoder return values - in case hidden sizes don't match
    # dec_hidden_tensor[0] = self.hidden_transform(enc_hidden_node)
    # if (dec_cell_tensor!=None) and (enc_cell_node!=None):
    #   dec_cell_tensor[0] = self.cell_transform(enc_cell_node)

    #run encoder and initialize decoder with hidden states
    dec_hidden_tensor, dec_cell_tensor, enc_final_hidden_layer = self.run_enc_init_dec(inputs)

    #decoder
    pred_out_tensor = torch.zeros(outputs.size(0), len(outputs[0]), self.decoder.vocab_size, device=device) #before was device = outputs.device

    print('this is the predicted out tensor size: {}'.format(pred_out_tensor.shape))

    for word_pos in range(0,len(outputs[0])):
      #get particular word position for entire batch and reshape to have 2d array
      word_batch = outputs[:,word_pos].unsqueeze(1)

      #decoder forward pass
      dec_hidden_tensor, dec_cell_tensor, pred_out = self.decoder.forward(word_batch, dec_hidden_tensor, dec_cell_tensor, enc_final_hidden_layer)

      print('decoder output type: {}'.format(type(pred_out)))
      display(pred_out)
      print('decoder output shape: {}'.format(pred_out.shape))

      #add value to prediction tensor
      pred_out_tensor[:, word_pos, :] = pred_out


    return pred_out_tensor #must make sure has shape (batch size, seq length, vocab size)


  def pred(self, inputs):

    #run encoder and initialize decoder with hidden states
    dec_hidden_tensor, dec_cell_tensor, enc_flayer = self.run_enc_init_dec(inputs)

    #init single value prediction
    size = (inputs.size(0), 1) #1 for each in batch
    prev_out_sing_tens = torch.full(size, self.sos_token)

    #init full prediction
    pred_out_all_tens = torch.zeros(inputs.size(0), self.max_length)

    print('\n\n\nThis is seq2seq predicted tensor size: {}'.format(pred_out_all_tens.shape))

    #mask for which seq endend
    cont_tens = torch.ones(inputs.size(0), dtype=torch.bool)

    #to check we don't exceed max length & index properly
    it = 0

    #continue while there are any sentences that are not finished
    #and we haven't reached a max length
    while mask_tens.any() and (it < self.max_length):

      #get unmasked values
      prev_out_sing_unmask = prev_out_sing_tens[mask_tens]
      hidden_unmask = dec_hidden_tensor[mask_tens]
      cell_unmask = dec_cell_tensor[mask_tens]

      #pass to decoder
      hidden_unmask, cell_unmask, pred_word_indx = self.decoder.pred(self, prev_out_sing_unmask, hidden_unmask, cell_unmask, enc_flayer)

      #change mask
      mask_tens = mask_tens & (pred_word_indx != self.eos_token)

      #add predicted words to running full prediction - if not <eos> and cont_tens=True
      indices_to_update = mask_tens.squeeze()
      pred_out_all_tens[indices_to_update, it] = pred_word_indx[indices_to_update].squeeze()

      #replace values where relevant
      prev_out_sing_tens[mask_tens] = pred_word_indx
      dec_hidden_tensor[mask_tens] = hidden_unmask
      dec_cell_tensor[mask_tens] = cell_unmask

      #update iterator
      it += 1


    return pred_out_all_tens


In [200]:
data_dict["English Vocabulary"]

{'<sos>': 1,
 '<eos>': 2,
 'are': 3,
 'going': 4,
 'hello': 5,
 'how': 6,
 'we': 7,
 'where': 8,
 'world': 9,
 'you': 10,
 '<pad>': 0}

In [201]:
#have to seperate by word
output[:,0].reshape(len(output),1)
# len(output)

tensor([[1],
        [1],
        [1]])

In [202]:

#encoder param
enc_node_type = "rnn"
enc_n_layers = 2
enc_hidden_dim = 4
enc_embed_dim = 7
eng_vocab_size = len(data_dict["English Vocabulary"])

#decoder_param
dec_node_type = "rnn"
dec_n_layers = 2
dec_hidden_dim = 6
dec_embed_dim = 8
it_vocab_size = len(data_dict["Italian Vocabulary"])

#seq2seq param
# max_length = 30
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# (self, node_type, n_layers, hidden_dim, embed_dim, vocab_size)
# (self, node_type, n_layers, hidden_dim, embed_dim, vocab_size, attention=False, max_length=30)

print('English vocab size: {}'.format(eng_vocab_size))
print('Italian vocab size: {}'.format(it_vocab_size))

#create seq2seq instance
encoder_args = (enc_node_type, enc_n_layers, enc_hidden_dim, enc_embed_dim, eng_vocab_size)
decoder_args = (dec_node_type, dec_n_layers, dec_hidden_dim, dec_embed_dim, it_vocab_size)
seq2seq = Seq2Seq(encoder_args, decoder_args).to(device)


temp = seq2seq.forward(input, output)
print('this is seq2seq forward output')
display(temp)
print("output shape: {}".format(temp.shape))
# print("output type: {}".format(type(temp)))
# #forward step

# #encoder instance
# encoder = EncoderNN(*encoder_args)
# enc_out, final_hidden_layer = encoder.forward(input)
# enc_hidden_node = enc_out[0]

# print('\n\n\nafter encoder test step')



# #decoder instance
# decoder = DecoderNN(*decoder_args)
# #initialize hidden and cell list
# dec_hidden_list, dec_cell_list = init_hidden(decoder, output.shape[0])
# dec_hidden_list[0] = enc_hidden_node

# pred_out = decoder.forward(output[:,0].reshape(len(output), 1), dec_hidden_list, None, final_hidden_layer)
# print('\nafter decoder test step')

# #create encoder instance
# encoder = EncoderNN(node_type, n_layers, hidden_dim, embed_dim, eng_vocab_size)

# #forward step
# hidden_list, final_hidden_layer = encoder.forward(input)

English vocab size: 11
Italian vocab size: 10
this is the predicted out tensor size: torch.Size([3, 5, 10])

this is the initial input of the decoder forward


tensor([[1],
        [1],
        [1]])

this is the type: <class 'torch.Tensor'>
this is the shape: torch.Size([3, 1])



decoder output type: <class 'torch.Tensor'>


tensor([[-0.0381,  0.2181, -0.5328, -2.4058, -0.2609, -1.5302, -0.1608, -0.1088,
          1.0435, -0.9356],
        [-0.0428,  0.2205, -0.5315, -2.4121, -0.2639, -1.5382, -0.1596, -0.1129,
          1.0441, -0.9384],
        [-0.0427,  0.2200, -0.5314, -2.4107, -0.2636, -1.5380, -0.1601, -0.1127,
          1.0440, -0.9383]], grad_fn=<PermuteBackward0>)

decoder output shape: torch.Size([3, 10])

this is the initial input of the decoder forward


tensor([[6],
        [4],
        [5]])

this is the type: <class 'torch.Tensor'>
this is the shape: torch.Size([3, 1])



decoder output type: <class 'torch.Tensor'>


tensor([[-0.3995, -1.0571, -1.4084, -1.4986, -1.1522, -2.3609, -0.1721,  0.3703,
          1.2977, -2.8812],
        [-0.5926, -1.0749, -1.2376, -0.8393, -1.3304, -2.2429, -0.0632,  0.6582,
          1.5270, -3.5346],
        [-0.5462, -1.0594, -1.3070, -0.9881, -1.3581, -2.1886,  0.0632,  0.5263,
          1.4178, -3.4444]], grad_fn=<PermuteBackward0>)

decoder output shape: torch.Size([3, 10])

this is the initial input of the decoder forward


tensor([[9],
        [7],
        [8]])

this is the type: <class 'torch.Tensor'>
this is the shape: torch.Size([3, 1])



decoder output type: <class 'torch.Tensor'>


tensor([[-0.1232, -0.7098, -1.1256, -1.6068, -0.7058, -2.4386, -0.3348,  0.1156,
          1.9247, -2.9962],
        [ 0.3294, -0.4000, -0.8865, -2.1563,  0.0954, -2.6435, -1.1198,  0.1930,
          2.5691, -2.3931],
        [ 0.3439, -0.1770, -0.5958, -1.8530,  0.2289, -2.6170, -1.1789,  0.3466,
          3.1392, -2.9147]], grad_fn=<PermuteBackward0>)

decoder output shape: torch.Size([3, 10])

this is the initial input of the decoder forward


tensor([[3],
        [2],
        [2]])

this is the type: <class 'torch.Tensor'>
this is the shape: torch.Size([3, 1])



decoder output type: <class 'torch.Tensor'>


tensor([[ 0.0659, -0.5383, -0.9010, -1.7731, -0.2289, -2.5508, -0.9917,  0.5392,
          2.4500, -2.7485],
        [-0.4310, -0.9511, -1.1549, -1.0945, -1.0278, -2.3444, -0.2543,  0.3805,
          1.5450, -3.0835],
        [-0.4507, -0.9931, -1.2257, -1.1155, -1.1206, -2.3009, -0.1582,  0.3915,
          1.4609, -3.1218]], grad_fn=<PermuteBackward0>)

decoder output shape: torch.Size([3, 10])

this is the initial input of the decoder forward


tensor([[2],
        [0],
        [0]])

this is the type: <class 'torch.Tensor'>
this is the shape: torch.Size([3, 1])



decoder output type: <class 'torch.Tensor'>


tensor([[-0.3531, -0.9294, -1.1598, -1.1807, -0.9356, -2.3693, -0.2760,  0.2318,
          1.5357, -2.9510],
        [ 0.3243, -0.1650, -0.7066, -2.1139,  0.1177, -2.5947, -0.8943, -0.0687,
          2.7245, -2.5976],
        [ 0.3334, -0.1848, -0.7087, -2.0744,  0.1281, -2.6016, -0.9362, -0.0037,
          2.7861, -2.6577]], grad_fn=<PermuteBackward0>)

decoder output shape: torch.Size([3, 10])
this is seq2seq forward output


tensor([[[-0.0381,  0.2181, -0.5328, -2.4058, -0.2609, -1.5302, -0.1608,
          -0.1088,  1.0435, -0.9356],
         [-0.3995, -1.0571, -1.4084, -1.4986, -1.1522, -2.3609, -0.1721,
           0.3703,  1.2977, -2.8812],
         [-0.1232, -0.7098, -1.1256, -1.6068, -0.7058, -2.4386, -0.3348,
           0.1156,  1.9247, -2.9962],
         [ 0.0659, -0.5383, -0.9010, -1.7731, -0.2289, -2.5508, -0.9917,
           0.5392,  2.4500, -2.7485],
         [-0.3531, -0.9294, -1.1598, -1.1807, -0.9356, -2.3693, -0.2760,
           0.2318,  1.5357, -2.9510]],

        [[-0.0428,  0.2205, -0.5315, -2.4121, -0.2639, -1.5382, -0.1596,
          -0.1129,  1.0441, -0.9384],
         [-0.5926, -1.0749, -1.2376, -0.8393, -1.3304, -2.2429, -0.0632,
           0.6582,  1.5270, -3.5346],
         [ 0.3294, -0.4000, -0.8865, -2.1563,  0.0954, -2.6435, -1.1198,
           0.1930,  2.5691, -2.3931],
         [-0.4310, -0.9511, -1.1549, -1.0945, -1.0278, -2.3444, -0.2543,
           0.3805,  1.5450, -3.0835],

output shape: torch.Size([3, 5, 10])


In [203]:
print('true output')
display(output)
print("true output shape: {}".format(output.shape))

true output


tensor([[1, 6, 9, 3, 2],
        [1, 4, 7, 2, 0],
        [1, 5, 8, 2, 0]])

true output shape: torch.Size([3, 5])


Notes:

- before running - write in comments how each dimension is looking like after each computation - helpful for debugging

- incorporate batches!

- transformers

- beam search

- bidirectional

- different attention methods

-- evaluate with Bleu scores


SHOULD ADD
- dependency parsing, pretraining, and fine-tuning

Run time notes:

- embedding size: Common values for the embedding dimension in NLP tasks range from 50 to 300, but larger values like 512 or 1024 can be used for more complex tasks or larger datasets.